services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: lAUVsdfLK2U9
      POSTGRES_DB: db_social_media_todo
    networks:
      - social_media_todo

  app:
    container_name: social_media_todo_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - social_media_todo
    environment:
      - DATABASE_URL=postgresql://root:lAUVsdfLK2U9@db:5432/db_social_media_todo?schema=public

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - social_media_todo
    depends_on:
      - db

networks:
  social_media_todo:
    driver: bridge
